//! The Infinity Slack bot: connects Slack (Socket Mode) to Infinity daemon
//! sessions, driving the Hydro dataflow from `infinity-slack-dataflow` as an
//! embedded DFIR graph around this binary's event loop.
//!
//! Layout:
//! - `dfir` (generated by `build.rs` via Hydro's embedded mode): the dataflow
//!   compiled to a plain function returning a manually-driven [`Dfir`] graph.
//! - [`slack_io`]: Slack Socket Mode WebSocket inbound + Web API outbound.
//! - [`daemon_io`] / [`daemon_client`]: per-thread daemon connections over
//!   the Unix socket.
//!
//! Events flow: `slack_io`/`daemon_io` tasks → mpsc → embedded dataflow →
//! synchronous output callbacks → mpsc → `slack_io`/`daemon_io` tasks.

use infinity_slack_dataflow::config::Config;
use infinity_slack_dataflow::runtime;
use infinity_slack_dataflow::session_store::SessionStore;
use tokio_stream::wrappers::ReceiverStream;

mod daemon_client;
mod daemon_io;
mod slack_client;
mod slack_io;

pub type BoxError = Box<dyn std::error::Error + Send + Sync>;

/// The Hydro dataflow, compiled to plain Rust by `build.rs` using
/// `generate_embedded`. Exposes `fn slack_bot(daemon_events, slack_events,
/// &mut slack_bot::EmbeddedOutputs { daemon_commands, slack_actions }) -> Dfir`.
#[expect(
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    reason = "generated code"
)]
#[allow(unused_imports, unused_qualifications, missing_docs, non_snake_case)]
mod dfir {
    include!(concat!(env!("OUT_DIR"), "/slack_bot_dfir.rs"));
}

fn init_tracing() {
    use tracing_subscriber::layer::SubscriberExt;
    use tracing_subscriber::util::SubscriberInitExt;

    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));
    let stderr_layer = tracing_subscriber::fmt::layer().with_writer(std::io::stderr);

    let log_path = std::env::var("SLACK_BOT_LOG").unwrap_or_else(|_| {
        infinity_protocol::state_dir()
            .join("slack.log")
            .to_string_lossy()
            .into_owned()
    });
    let file_layer = {
        let file = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&log_path)
            .unwrap_or_else(|e| panic!("failed to open log file {log_path}: {e}"));
        tracing_subscriber::fmt::layer()
            .with_writer(std::sync::Mutex::new(file))
            .with_ansi(false)
    };

    tracing_subscriber::registry()
        .with(env_filter)
        .with(stderr_layer)
        .with(file_layer)
        .try_init()
        .expect("bug: tracing subscriber initialized twice");
}

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    init_tracing();

    // Bootstrap config, session store, and the shared runtime state that the
    // dataflow's closures access via `runtime::get()`.
    let config: &'static Config = Box::leak(Box::new(Config::load()?));
    let store_path = infinity_protocol::state_dir().join("slack_sessions.json");
    let store = SessionStore::load(store_path)?;
    let sessions = std::sync::Arc::new(std::sync::Mutex::new(store));
    runtime::init(config, sessions);

    // I/O tasks. Each returns (inbound events receiver, outbound sender).
    let (slack_events_rx, slack_actions_tx) = slack_io::spawn(config);
    let (daemon_events_rx, daemon_commands_tx) = daemon_io::spawn();

    // Output callbacks fire synchronously while the dataflow ticks; they hand
    // work off to the async I/O tasks through unbounded channels (see
    // `slack_io::spawn` / `daemon_io::spawn` for the backpressure rationale).
    let mut outputs = dfir::slack_bot::EmbeddedOutputs {
        daemon_commands: move |command| {
            if daemon_commands_tx.send(command).is_err() {
                tracing::error!("daemon I/O task is gone, dropping command");
            }
        },
        slack_actions: move |action| {
            if slack_actions_tx.send(action).is_err() {
                tracing::error!("Slack I/O task is gone, dropping action");
            }
        },
    };

    let mut flow = dfir::slack_bot(
        ReceiverStream::new(daemon_events_rx),
        ReceiverStream::new(slack_events_rx),
        &mut outputs,
    );

    tracing::info!("infinity-slack-bot running (Hydro embedded dataflow)");

    // DFIR graphs are !Send; drive the dataflow on a LocalSet until ctrl-c.
    let local = tokio::task::LocalSet::new();
    local
        .run_until(async {
            tokio::select! {
                _ = flow.run() => unreachable!("bug: Dfir::run returns Never"),
                result = tokio::signal::ctrl_c() => {
                    result.expect("failed to listen for ctrl-c");
                    tracing::info!("shutting down");
                }
            }
        })
        .await;

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;

    use infinity_slack_dataflow::daemon::DaemonCommand;
    use infinity_slack_dataflow::slack::SlackEvent;
    use tokio_stream::wrappers::ReceiverStream;

    /// Drives the *generated embedded* dataflow (the artifact `build.rs`
    /// produced) end to end: a chat message goes in, a `CreateSession`
    /// daemon command comes out. The sim tests in `infinity-slack-dataflow`
    /// validate the dataflow's semantics; this validates the embedded
    /// compilation and wiring.
    #[tokio::test]
    async fn embedded_flow_produces_create_session() {
        infinity_slack_dataflow::runtime::ensure_test_init();

        let (slack_tx, slack_rx) = tokio::sync::mpsc::channel::<SlackEvent>(8);
        let (_daemon_tx, daemon_rx) = tokio::sync::mpsc::channel(8);

        let slack_actions = RefCell::new(Vec::new());
        let daemon_commands = RefCell::new(Vec::new());
        let mut outputs = crate::dfir::slack_bot::EmbeddedOutputs {
            daemon_commands: |command| daemon_commands.borrow_mut().push(command),
            slack_actions: |action| slack_actions.borrow_mut().push(action),
        };

        slack_tx
            .send(SlackEvent {
                user: "U1".into(),
                text: "hello".into(),
                channel: "C1".into(),
                thread_ts: "100.1".into(),
                is_button_click: false,
                button_value: None,
                action_id: None,
                message_ts: None,
                button_text: None,
                is_bot: false,
                is_unauthorized: false,
                slash_command: None,
                response_url: None,
                trigger_id: None,
                is_app_home_opened: false,
            })
            .await
            .expect("send should succeed");
        drop(slack_tx);
        drop(_daemon_tx);

        let mut flow = crate::dfir::slack_bot(
            ReceiverStream::new(daemon_rx),
            ReceiverStream::new(slack_rx),
            &mut outputs,
        );
        tokio::task::LocalSet::new()
            .run_until(flow.run_available())
            .await;
        drop(flow);

        let commands = daemon_commands.into_inner();
        assert!(
            commands
                .iter()
                .any(|c| matches!(c, DaemonCommand::CreateSession { thread_ts, .. } if thread_ts == "100.1")),
            "expected a CreateSession command, got: {commands:?}"
        );
    }
}
