import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  infinityCodeSidebar: [
    {type: 'autogenerated', dirName: 'infinity-code'},
  ],
  infinityRuntimeSidebar: [
    {type: 'autogenerated', dirName: 'infinity-runtime'},
  ],
  rapSidebar: [
    {
      type: 'html',
      value: '<h4>Documentation</h4>',
      defaultStyle: true,
    },
    {type: 'doc' as const, id: 'rap/what-is-rap'},
    {
      type: 'category',
      label: 'About RAP',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'rap/about'}],
    },
    {
      type: 'category',
      label: 'Develop with RAP',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'rap/using-rap'}],
    },
    {
      type: 'html',
      value: '<h4 class="with-border">Specification</h4>',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'rap/spec'},
  ],
};

export default sidebars;
